# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_chunked_long <- function(filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_, skip, isGzipped, encoding, progress) {
    invisible(.Call(`_hipread_read_chunked_long`, filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_, skip, isGzipped, encoding, progress))
}

read_chunked_list <- function(filename, callback, chunksize, var_names_, var_types_, rt_info_, var_pos_info_, var_opts_, skip, isGzipped, encoding, progress) {
    invisible(.Call(`_hipread_read_chunked_list`, filename, callback, chunksize, var_names_, var_types_, rt_info_, var_pos_info_, var_opts_, skip, isGzipped, encoding, progress))
}

read_freqs <- function(filename, var_names, rt_info_, var_pos_info_, isGzipped, progress) {
    .Call(`_hipread_read_freqs`, filename, var_names, rt_info_, var_pos_info_, isGzipped, progress)
}

read_long <- function(filename, var_names, var_types, rt_info_, var_pos_info_, var_opts_, skip, n_max, isGzipped, encoding, progress) {
    .Call(`_hipread_read_long`, filename, var_names, var_types, rt_info_, var_pos_info_, var_opts_, skip, n_max, isGzipped, encoding, progress)
}

read_list <- function(filename, var_names_, var_types_, rt_info_, var_pos_info_, var_opts_, skip, n_max, isGzipped, encoding, progress) {
    .Call(`_hipread_read_list`, filename, var_names_, var_types_, rt_info_, var_pos_info_, var_opts_, skip, n_max, isGzipped, encoding, progress)
}

start_yield <- function(filename, isGzipped, skip) {
    .Call(`_hipread_start_yield`, filename, isGzipped, skip)
}

reset_yield <- function(data, skip) {
    invisible(.Call(`_hipread_reset_yield`, data, skip))
}

yield_is_done <- function(data) {
    .Call(`_hipread_yield_is_done`, data)
}

next_yield_long <- function(data, var_names, var_types, rt_info_, var_pos_info_, var_opts_, yield_size, encoding) {
    .Call(`_hipread_next_yield_long`, data, var_names, var_types, rt_info_, var_pos_info_, var_opts_, yield_size, encoding)
}

next_yield_list <- function(data, var_names_, var_types_, rt_info_, var_pos_info_, var_opts_, yield_size, encoding) {
    .Call(`_hipread_next_yield_list`, data, var_names_, var_types_, rt_info_, var_pos_info_, var_opts_, yield_size, encoding)
}

