# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

engine_main <- function(subsetAtomsList, sigma, maxit, tol, showprog = FALSE, myfname = "mpost.euc") {
    .Call('_SBmedian_engine_main', PACKAGE = 'SBmedian', subsetAtomsList, sigma, maxit, tol, showprog, myfname)
}

