# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Strip out BOM from JSON data
#'
#' @param x The GET return to strip BOM out of
#' @export
mnis_bom <- function(x) {
    .Call(`_mnis_mnis_bom`, x)
}

