# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

charSepXPtr <- function(path, n, m, r) {
    .Call(`_mmapcharr_charSepXPtr`, path, n, m, r)
}

extractVec <- function(e, elemInd) {
    .Call(`_mmapcharr_extractVec`, e, elemInd)
}

extractMat <- function(e, rowInd, colInd) {
    .Call(`_mmapcharr_extractMat`, e, rowInd, colInd)
}

nline_cpp <- function(obj) {
    .Call(`_mmapcharr_nline_cpp`, obj)
}

