// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4Beta_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Beta_phi_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4FB_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4FB_phi_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4VIB_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4VIB_phi_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4Beta_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Beta_mod, 0},
    {"_rcpp_module_boot_stan_fit4Beta_phi_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Beta_phi_mod, 0},
    {"_rcpp_module_boot_stan_fit4FB_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4FB_mod, 0},
    {"_rcpp_module_boot_stan_fit4FB_phi_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4FB_phi_mod, 0},
    {"_rcpp_module_boot_stan_fit4VIB_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4VIB_mod, 0},
    {"_rcpp_module_boot_stan_fit4VIB_phi_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4VIB_phi_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_FlexReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
