# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eval_marker_cpp <- function(B, m, Sout) {
    invisible(.Call(`_SimSurvNMarker_eval_marker`, B, m, Sout))
}

get_commutation <- function(n, m) {
    .Call(`_SimSurvNMarker_get_commutation`, n, m)
}

#' Get Gauss–Legendre Quadrature Nodes and Weights
#' @description
#' Computes Gauss–Legendre Quadrature nodes and weights.
#'
#' @param n number of nodes.
#'
#' @examples
#' library(SimSurvNMarker)
#' get_gl_rule(4)
#' get_gl_rule(25)
#'
#' # fast
#' system.time(replicate(10000, get_gl_rule(10)))
#' system.time(replicate(10000, get_gl_rule(100)))
#' @export
get_gl_rule <- function(n) {
    .Call(`_SimSurvNMarker_get_gl_rule`, n)
}

glq <- function(lb, ub, nodes, weights, f, rho) {
    .Call(`_SimSurvNMarker_glq`, lb, ub, nodes, weights, f, rho)
}

get_ns_ptr <- function(knots, boundary_knots, intercept) {
    .Call(`_SimSurvNMarker_get_ns_ptr`, knots, boundary_knots, intercept)
}

ns_cpp <- function(x, ns_ptr) {
    .Call(`_SimSurvNMarker_ns_cpp`, x, ns_ptr)
}

