// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countlines
long countlines(std::string fn);
RcppExport SEXP _collUtils_countlines(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    rcpp_result_gen = Rcpp::wrap(countlines(fn));
    return rcpp_result_gen;
END_RCPP
}
// ncols
long ncols(std::string fn);
RcppExport SEXP _collUtils_ncols(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    rcpp_result_gen = Rcpp::wrap(ncols(fn));
    return rcpp_result_gen;
END_RCPP
}
// readcol
std::vector< std::string > readcol(std::string fileName, long colNum, long nSkip, long maxRowNum);
RcppExport SEXP _collUtils_readcol(SEXP fileNameSEXP, SEXP colNumSEXP, SEXP nSkipSEXP, SEXP maxRowNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< long >::type colNum(colNumSEXP);
    Rcpp::traits::input_parameter< long >::type nSkip(nSkipSEXP);
    Rcpp::traits::input_parameter< long >::type maxRowNum(maxRowNumSEXP);
    rcpp_result_gen = Rcpp::wrap(readcol(fileName, colNum, nSkip, maxRowNum));
    return rcpp_result_gen;
END_RCPP
}
// readcols
Rcpp::CharacterMatrix readcols(std::string fn, std::vector<long> colsel, long nFirstSkipLines, long nSkipUnit);
RcppExport SEXP _collUtils_readcols(SEXP fnSEXP, SEXP colselSEXP, SEXP nFirstSkipLinesSEXP, SEXP nSkipUnitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< std::vector<long> >::type colsel(colselSEXP);
    Rcpp::traits::input_parameter< long >::type nFirstSkipLines(nFirstSkipLinesSEXP);
    Rcpp::traits::input_parameter< long >::type nSkipUnit(nSkipUnitSEXP);
    rcpp_result_gen = Rcpp::wrap(readcols(fn, colsel, nFirstSkipLines, nSkipUnit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_collUtils_countlines", (DL_FUNC) &_collUtils_countlines, 1},
    {"_collUtils_ncols", (DL_FUNC) &_collUtils_ncols, 1},
    {"_collUtils_readcol", (DL_FUNC) &_collUtils_readcol, 4},
    {"_collUtils_readcols", (DL_FUNC) &_collUtils_readcols, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_collUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
