# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disaggregate_mdCPP <- function(macro_data) {
    .Call('_synthACS_disaggregate_mdCPP', PACKAGE = 'synthACS', macro_data)
}

