// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// hsar_cpp_arma
List hsar_cpp_arma(arma::mat X, arma::vec y, arma::sp_mat W, arma::sp_mat M, arma::sp_mat Z, arma::mat detval, arma::mat detvalM, arma::vec Unum, int burnin, int Nsim, int thinning, float rho_start, float lambda_start, float sigma2e_start, float sigma2u_start, arma::vec betas_start);
RcppExport SEXP _HSAR_hsar_cpp_arma(SEXP XSEXP, SEXP ySEXP, SEXP WSEXP, SEXP MSEXP, SEXP ZSEXP, SEXP detvalSEXP, SEXP detvalMSEXP, SEXP UnumSEXP, SEXP burninSEXP, SEXP NsimSEXP, SEXP thinningSEXP, SEXP rho_startSEXP, SEXP lambda_startSEXP, SEXP sigma2e_startSEXP, SEXP sigma2u_startSEXP, SEXP betas_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type detval(detvalSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type detvalM(detvalMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Unum(UnumSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type Nsim(NsimSEXP);
    Rcpp::traits::input_parameter< int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< float >::type rho_start(rho_startSEXP);
    Rcpp::traits::input_parameter< float >::type lambda_start(lambda_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2e_start(sigma2e_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2u_start(sigma2u_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betas_start(betas_startSEXP);
    rcpp_result_gen = Rcpp::wrap(hsar_cpp_arma(X, y, W, M, Z, detval, detvalM, Unum, burnin, Nsim, thinning, rho_start, lambda_start, sigma2e_start, sigma2u_start, betas_start));
    return rcpp_result_gen;
END_RCPP
}
// hsar_cpp_arma_lambda_0
List hsar_cpp_arma_lambda_0(arma::mat X, arma::vec y, arma::sp_mat W, arma::sp_mat Z, arma::mat detval, arma::vec Unum, int burnin, int Nsim, int thinning, float rho_start, float sigma2e_start, float sigma2u_start, arma::vec betas_start);
RcppExport SEXP _HSAR_hsar_cpp_arma_lambda_0(SEXP XSEXP, SEXP ySEXP, SEXP WSEXP, SEXP ZSEXP, SEXP detvalSEXP, SEXP UnumSEXP, SEXP burninSEXP, SEXP NsimSEXP, SEXP thinningSEXP, SEXP rho_startSEXP, SEXP sigma2e_startSEXP, SEXP sigma2u_startSEXP, SEXP betas_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type detval(detvalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Unum(UnumSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type Nsim(NsimSEXP);
    Rcpp::traits::input_parameter< int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< float >::type rho_start(rho_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2e_start(sigma2e_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2u_start(sigma2u_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betas_start(betas_startSEXP);
    rcpp_result_gen = Rcpp::wrap(hsar_cpp_arma_lambda_0(X, y, W, Z, detval, Unum, burnin, Nsim, thinning, rho_start, sigma2e_start, sigma2u_start, betas_start));
    return rcpp_result_gen;
END_RCPP
}
// hsar_cpp_arma_rho_0
List hsar_cpp_arma_rho_0(arma::mat X, arma::vec y, arma::sp_mat M, arma::sp_mat Z, arma::mat detvalM, arma::vec Unum, int burnin, int Nsim, int thinning, float lambda_start, float sigma2e_start, float sigma2u_start, arma::vec betas_start);
RcppExport SEXP _HSAR_hsar_cpp_arma_rho_0(SEXP XSEXP, SEXP ySEXP, SEXP MSEXP, SEXP ZSEXP, SEXP detvalMSEXP, SEXP UnumSEXP, SEXP burninSEXP, SEXP NsimSEXP, SEXP thinningSEXP, SEXP lambda_startSEXP, SEXP sigma2e_startSEXP, SEXP sigma2u_startSEXP, SEXP betas_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type detvalM(detvalMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Unum(UnumSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type Nsim(NsimSEXP);
    Rcpp::traits::input_parameter< int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< float >::type lambda_start(lambda_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2e_start(sigma2e_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2u_start(sigma2u_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betas_start(betas_startSEXP);
    rcpp_result_gen = Rcpp::wrap(hsar_cpp_arma_rho_0(X, y, M, Z, detvalM, Unum, burnin, Nsim, thinning, lambda_start, sigma2e_start, sigma2u_start, betas_start));
    return rcpp_result_gen;
END_RCPP
}
// sar_cpp_arma
List sar_cpp_arma(arma::mat X, arma::vec y, arma::sp_mat W, arma::mat detval, int burnin, int Nsim, int thinning, float rho_start, float sigma2e_start, arma::vec betas_start);
RcppExport SEXP _HSAR_sar_cpp_arma(SEXP XSEXP, SEXP ySEXP, SEXP WSEXP, SEXP detvalSEXP, SEXP burninSEXP, SEXP NsimSEXP, SEXP thinningSEXP, SEXP rho_startSEXP, SEXP sigma2e_startSEXP, SEXP betas_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type detval(detvalSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type Nsim(NsimSEXP);
    Rcpp::traits::input_parameter< int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< float >::type rho_start(rho_startSEXP);
    Rcpp::traits::input_parameter< float >::type sigma2e_start(sigma2e_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betas_start(betas_startSEXP);
    rcpp_result_gen = Rcpp::wrap(sar_cpp_arma(X, y, W, detval, burnin, Nsim, thinning, rho_start, sigma2e_start, betas_start));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HSAR_hsar_cpp_arma", (DL_FUNC) &_HSAR_hsar_cpp_arma, 16},
    {"_HSAR_hsar_cpp_arma_lambda_0", (DL_FUNC) &_HSAR_hsar_cpp_arma_lambda_0, 13},
    {"_HSAR_hsar_cpp_arma_rho_0", (DL_FUNC) &_HSAR_hsar_cpp_arma_rho_0, 13},
    {"_HSAR_sar_cpp_arma", (DL_FUNC) &_HSAR_sar_cpp_arma, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_HSAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
