# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glmdeploy_cpp <- function(dataFields, arguments, family, link_function, interceptname, hasfactors, filename_in, outlanguage, path_in) {
    invisible(.Call(`_glm_deploy_glmdeploy_cpp`, dataFields, arguments, family, link_function, interceptname, hasfactors, filename_in, outlanguage, path_in))
}

