genepop:
  skin: "purple"
  heading: " Genepop shiny : ISE-M "
  latex_path: !expr system.file('doc', 'genepop.pdf', package='genepop')
  mode_debug: FALSE
  version: "0.1"
  version_genepop: !expr genepop::getVersion()
  spinner: "spinner9.gif"
  color:
    param: "primary"
    dowload: "primary"
    result: "primary"
    help: "warning"
    input: "primary"
    runButton: "color: #fff; background-color: #337ab7; border-color: #2e6da4"
    dowloadButton: "btn-primary"
    stopButton: "color: #fff; background-color: #e74c3c; border-color: #c0392b"
  opts:
    o11:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o12:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o13:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o14:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o15:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o21:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o31:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o32:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o33:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500
    o34:
      Dememo:
        min: 100 
        max: 100000
        step: 10
        value: 10000
      Nbatches:
        min: 10 
        max: 1000
        step: 10
        value: 100
      Niters:
        min: 400
        max: 5000
        step: 10
        value: 500

