// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// screen_cpp
arma::mat screen_cpp(const arma::mat& x, const arma::vec& y, const int num_keep, const bool square, const bool main_effect);
RcppExport SEXP _sprintr_screen_cpp(SEXP xSEXP, SEXP ySEXP, SEXP num_keepSEXP, SEXP squareSEXP, SEXP main_effectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type num_keep(num_keepSEXP);
    Rcpp::traits::input_parameter< const bool >::type square(squareSEXP);
    Rcpp::traits::input_parameter< const bool >::type main_effect(main_effectSEXP);
    rcpp_result_gen = Rcpp::wrap(screen_cpp(x, y, num_keep, square, main_effect));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sprintr_screen_cpp", (DL_FUNC) &_sprintr_screen_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sprintr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
