// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BigQuicHelper
void BigQuicHelper(std::vector<std::string> argvPasser);
RcppExport SEXP _BigQuic_BigQuicHelper(SEXP argvPasserSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type argvPasser(argvPasserSEXP);
    BigQuicHelper(argvPasser);
    return R_NilValue;
END_RCPP
}
