// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SpaTimeClusCpp
S4 SpaTimeClusCpp(S4 input, List inputparam, NumericMatrix matT);
RcppExport SEXP _SpaTimeClus_SpaTimeClusCpp(SEXP inputSEXP, SEXP inputparamSEXP, SEXP matTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type input(inputSEXP);
    Rcpp::traits::input_parameter< List >::type inputparam(inputparamSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type matT(matTSEXP);
    rcpp_result_gen = Rcpp::wrap(SpaTimeClusCpp(input, inputparam, matT));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpaTimeClus_SpaTimeClusCpp", (DL_FUNC) &_SpaTimeClus_SpaTimeClusCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpaTimeClus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
