// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// datassimcpp
List datassimcpp(arma::mat& pred, arma::mat& var, arma::mat Corr);
RcppExport SEXP _DatAssim_datassimcpp(SEXP predSEXP, SEXP varSEXP, SEXP CorrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Corr(CorrSEXP);
    rcpp_result_gen = Rcpp::wrap(datassimcpp(pred, var, Corr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DatAssim_datassimcpp", (DL_FUNC) &_DatAssim_datassimcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DatAssim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
