# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hypergeom_Cplx_Cplx <- function(m, a, b, x, alpha) {
    .Call('_HypergeoMat_hypergeom_Cplx_Cplx', PACKAGE = 'HypergeoMat', m, a, b, x, alpha)
}

hypergeom_R_R <- function(m, a, b, x, alpha) {
    .Call('_HypergeoMat_hypergeom_R_R', PACKAGE = 'HypergeoMat', m, a, b, x, alpha)
}

hypergeom_Cplx_R <- function(m, a, b, x, alpha) {
    .Call('_HypergeoMat_hypergeom_Cplx_R', PACKAGE = 'HypergeoMat', m, a, b, x, alpha)
}

hypergeom_R_Cplx <- function(m, a, b, x, alpha) {
    .Call('_HypergeoMat_hypergeom_R_Cplx', PACKAGE = 'HypergeoMat', m, a, b, x, alpha)
}

