# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countMatches_cpp <- function(inter) {
    .Call('_mapi_countMatches_cpp', PACKAGE = 'mapi', inter)
}

getValues_cpp <- function(cells, inter, weights, values) {
    .Call('_mapi_getValues_cpp', PACKAGE = 'mapi', cells, inter, weights, values)
}

parseInter_cpp <- function(cells, inter, weights, values) {
    .Call('_mapi_parseInter_cpp', PACKAGE = 'mapi', cells, inter, weights, values)
}

parseInterPerm_cpp <- function(cells, inter, weights, values) {
    .Call('_mapi_parseInterPerm_cpp', PACKAGE = 'mapi', cells, inter, weights, values)
}

mkP4st_cpp <- function(r, N, ecc) {
    .Call('_mapi_mkP4st_cpp', PACKAGE = 'mapi', r, N, ecc)
}

