// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lmatch_cpp
SEXP lmatch_cpp(SEXP rv, SEXP rvo, SEXP rtab, SEXP rtabo, SEXP rna_incomp);
RcppExport SEXP _ldat_lmatch_cpp(SEXP rvSEXP, SEXP rvoSEXP, SEXP rtabSEXP, SEXP rtaboSEXP, SEXP rna_incompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rv(rvSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rvo(rvoSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rtab(rtabSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rtabo(rtaboSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rna_incomp(rna_incompSEXP);
    rcpp_result_gen = Rcpp::wrap(lmatch_cpp(rv, rvo, rtab, rtabo, rna_incomp));
    return rcpp_result_gen;
END_RCPP
}
// order_ldat_cpp
SEXP order_ldat_cpp(Rcpp::List veclist);
RcppExport SEXP _ldat_order_ldat_cpp(SEXP veclistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type veclist(veclistSEXP);
    rcpp_result_gen = Rcpp::wrap(order_ldat_cpp(veclist));
    return rcpp_result_gen;
END_RCPP
}
// partial_order_cpp
SEXP partial_order_cpp(SEXP rv, SEXP rpivots);
RcppExport SEXP _ldat_partial_order_cpp(SEXP rvSEXP, SEXP rpivotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rv(rvSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rpivots(rpivotsSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_order_cpp(rv, rpivots));
    return rcpp_result_gen;
END_RCPP
}
// partial_sort_cpp
SEXP partial_sort_cpp(SEXP rv, SEXP rpivots);
RcppExport SEXP _ldat_partial_sort_cpp(SEXP rvSEXP, SEXP rpivotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rv(rvSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rpivots(rpivotsSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_sort_cpp(rv, rpivots));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ldat_lmatch_cpp", (DL_FUNC) &_ldat_lmatch_cpp, 5},
    {"_ldat_order_ldat_cpp", (DL_FUNC) &_ldat_order_ldat_cpp, 1},
    {"_ldat_partial_order_cpp", (DL_FUNC) &_ldat_partial_order_cpp, 2},
    {"_ldat_partial_sort_cpp", (DL_FUNC) &_ldat_partial_sort_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ldat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
