SOURCE_CPP = ./src

all:
	@echo "\nCompile Genepop: \n"
	g++ -o Genepop $(SOURCE_CPP)/*.cpp -O3
	@echo "\nCompile finish\n"

clean:
	rm -f Genepop

cleanR:
	rm -f $(SOURCE_CPP)/*.o
	rm -f $(SOURCE_CPP)/*.so
