// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// htdpinit
void htdpinit();
RcppExport SEXP _htdp_htdpinit() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    htdpinit();
    return R_NilValue;
END_RCPP
}
// displace
DataFrame displace(NumericMatrix xy, Date t0, Date t1, int iopt);
RcppExport SEXP _htdp_displace(SEXP xySEXP, SEXP t0SEXP, SEXP t1SEXP, SEXP ioptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< Date >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< Date >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< int >::type iopt(ioptSEXP);
    rcpp_result_gen = Rcpp::wrap(displace(xy, t0, t1, iopt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_htdp_htdpinit", (DL_FUNC) &_htdp_htdpinit, 0},
    {"_htdp_displace", (DL_FUNC) &_htdp_displace, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_htdp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
