# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

writeDTable <- function(path, data) {
    invisible(.Call(`_DataGraph_writeDTable`, path, data))
}

openDTable <- function(path) {
    invisible(.Call(`_DataGraph_openDTable`, path))
}

syncDTable <- function(path) {
    invisible(.Call(`_DataGraph_syncDTable`, path))
}

closeDTable <- function(path) {
    invisible(.Call(`_DataGraph_closeDTable`, path))
}

addDTable <- function(path, data) {
    invisible(.Call(`_DataGraph_addDTable`, path, data))
}

openDTBin <- function(path) {
    invisible(.Call(`_DataGraph_openDTBin`, path))
}

closeDTBin <- function(path) {
    invisible(.Call(`_DataGraph_closeDTBin`, path))
}

syncDTBin <- function(path) {
    invisible(.Call(`_DataGraph_syncDTBin`, path))
}

infoDTBin <- function(path = "") {
    invisible(.Call(`_DataGraph_infoDTBin`, path))
}

addDTBin <- function(path, name, data, time = NA_real_) {
    invisible(.Call(`_DataGraph_addDTBin`, path, name, data, time))
}

