---
title: "Quaternions are a special case of Clifford algebra"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("clifford")
library("onion")
```


The Broome Bridge insight:

\[
\mathbf{i}^2=
\mathbf{j}^2=
\mathbf{k}^2=
\mathbf{i}\mathbf{j}\mathbf{k}=-1
\]

The BBI and associativity together imply

\[
\mathbf{j}\mathbf{k}=-\mathbf{k}\mathbf{j}=\mathbf{i}\qquad
\mathbf{k}\mathbf{i}=-\mathbf{i}\mathbf{k}=\mathbf{j}\qquad
\mathbf{i}\mathbf{j}=-\mathbf{j}\mathbf{i}=\mathbf{k}\qquad
\]

and if we require a distributive algebra we get the quaternions.  A
general quaternion is of the form
$a+\mathbf{i}b+\mathbf{j}c+\mathbf{k}d$; addition is componentwise and
multiplication follows from the above.

A rotation operator $\mathbf{R}$ is generally written in the form

\[
\mathbf{R}=\cos\frac{\theta}{2} - \left(
n^1\mathbf{i}+
n^2\mathbf{j}+
n^3\mathbf{k}
\right)\sin\frac{\theta}{2}
\]

In the theory of Clifford algebra, a rotor $\mathbf{R}$ is represented as

\newcommand{\e}[1]{\mathbf{e}_{#1}}

\[
\mathbf{R}=\cos\frac{\theta}{2} + \left(
n^1\e{23}+
n^2\e{31}+
n^3\e{12}
\right)\sin\frac{\theta}{2}
\]

and this suggests that we identify $\mathbf{i},\mathbf{j},\mathbf{k}$
with $-\e{23},-\e{31},-\e{12}$ respectively.  Thus for example we may
verify that $\mathbf{i}\mathbf{j}=\mathbf{k}$:

\[
(-\e{23})(-\e{31})=\e{2331}=\e{21}=-\e{12}=\mathbf{k}
\]
