# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name logLikMultiNorm
#' @title Log likelihood function for multivariate normal with spatial dependency.
#'
#' @param mCoef coefficient matrix. Each column is the coefficient from a curve;
#' @param mDist distance matris;
#' @param s2 variance from the covariance model;
#' @param phi variance from the covariance model;
#' @param rho variance from the covariance model;
#' @export
NULL

logLikMultiNorm <- function(mCoef, mDist, s2, phi, p) {
    .Call(`_geoFKF_logLikMultiNorm`, mCoef, mDist, s2, phi, p)
}

