# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_set_cover2 <- function(i0, i1, group_sizes_i0, group_sizes_i1) {
    .Call(`_RcppGreedySetCover_greedy_set_cover2`, i0, i1, group_sizes_i0, group_sizes_i1)
}

