# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dblpm_posterior <- function(T, N, M, L, D, edgelist, x, w, gamma, beta, tauw, tauw0, taugamma, taugamma0, taubeta, taubeta0, taux, delta, aw, bw, agamma, bgamma, abeta, bbeta) {
    .Call(`_IrishDirectorates_cpp_dblpm_posterior`, T, N, M, L, D, edgelist, x, w, gamma, beta, tauw, tauw0, taugamma, taugamma0, taubeta, taubeta0, taux, delta, aw, bw, agamma, bgamma, abeta, bbeta)
}

cpp_dblpm_mcmc <- function(T, N, M, L, D, edgelist, x, w, gamma, beta, tauw, tauw0, taugamma, taugamma0, taubeta, taubeta0, taux, delta, aw, bw, agamma, bgamma, abeta, bbeta, niter, burnin, thin, x_var, w_var, gamma_var, beta_var, verbose) {
    .Call(`_IrishDirectorates_cpp_dblpm_mcmc`, T, N, M, L, D, edgelist, x, w, gamma, beta, tauw, tauw0, taugamma, taugamma0, taubeta, taubeta0, taux, delta, aw, bw, agamma, bgamma, abeta, bbeta, niter, burnin, thin, x_var, w_var, gamma_var, beta_var, verbose)
}

