#!/bin/sh
# This script is called whenever a package is built, and after configure is called.
# It removes the config log files and the system-dependent Makevars file that is created
# from the configure file.

rm -rf config.* src/Makevars
