# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EigenR_det_real <- function(M) {
    .Call('_EigenR_EigenR_det_real', PACKAGE = 'EigenR', M)
}

EigenR_det_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_det_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_det_sparse_real <- function(i, j, Mij, nrows, ncols) {
    .Call('_EigenR_EigenR_det_sparse_real', PACKAGE = 'EigenR', i, j, Mij, nrows, ncols)
}

EigenR_det_sparse_cplx <- function(i, j, Mij, nrows, ncols) {
    .Call('_EigenR_EigenR_det_sparse_cplx', PACKAGE = 'EigenR', i, j, Mij, nrows, ncols)
}

EigenR_rank_real <- function(M) {
    .Call('_EigenR_EigenR_rank_real', PACKAGE = 'EigenR', M)
}

EigenR_rank_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_rank_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_inverse_real <- function(M) {
    .Call('_EigenR_EigenR_inverse_real', PACKAGE = 'EigenR', M)
}

EigenR_inverse_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_inverse_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_kernel_COD_real <- function(M) {
    .Call('_EigenR_EigenR_kernel_COD_real', PACKAGE = 'EigenR', M)
}

EigenR_kernel_COD_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_kernel_COD_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_kernel_LU_real <- function(M) {
    .Call('_EigenR_EigenR_kernel_LU_real', PACKAGE = 'EigenR', M)
}

EigenR_kernel_LU_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_kernel_LU_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_image_LU_real <- function(M) {
    .Call('_EigenR_EigenR_image_LU_real', PACKAGE = 'EigenR', M)
}

EigenR_image_LU_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_image_LU_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_image_QR_real <- function(M) {
    .Call('_EigenR_EigenR_image_QR_real', PACKAGE = 'EigenR', M)
}

EigenR_image_QR_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_image_QR_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_image_COD_real <- function(M) {
    .Call('_EigenR_EigenR_image_COD_real', PACKAGE = 'EigenR', M)
}

EigenR_image_COD_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_image_COD_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_QR_real <- function(M) {
    .Call('_EigenR_EigenR_QR_real', PACKAGE = 'EigenR', M)
}

EigenR_QR_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_QR_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_chol_real <- function(M) {
    .Call('_EigenR_EigenR_chol_real', PACKAGE = 'EigenR', M)
}

EigenR_chol_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_chol_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_chol_sparse_real <- function(i, j, Mij, nrows, ncols) {
    .Call('_EigenR_EigenR_chol_sparse_real', PACKAGE = 'EigenR', i, j, Mij, nrows, ncols)
}

EigenR_chol_sparse_cplx <- function(i, j, Mij, nrows, ncols) {
    .Call('_EigenR_EigenR_chol_sparse_cplx', PACKAGE = 'EigenR', i, j, Mij, nrows, ncols)
}

EigenR_UtDU_real <- function(M) {
    .Call('_EigenR_EigenR_UtDU_real', PACKAGE = 'EigenR', M)
}

EigenR_UtDU_cplx <- function(Re, Im) {
    .Call('_EigenR_EigenR_UtDU_cplx', PACKAGE = 'EigenR', Re, Im)
}

EigenR_lsSolve_real <- function(A, b) {
    .Call('_EigenR_EigenR_lsSolve_real', PACKAGE = 'EigenR', A, b)
}

EigenR_lsSolve_cplx <- function(ReA, ImA, Reb, Imb) {
    .Call('_EigenR_EigenR_lsSolve_cplx', PACKAGE = 'EigenR', ReA, ImA, Reb, Imb)
}

