# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

est_param <- function(xr, xu, kappa, m, n, p, ciold, phi, chiold, lambda2, lambdag, lambdagold, intercept, unpen, posterior, elbo, start) {
    .Call(`_gren_est_param`, xr, xu, kappa, m, n, p, ciold, phi, chiold, lambda2, lambdag, lambdagold, intercept, unpen, posterior, elbo, start)
}

