// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// data_sailr_cpp_execute
Rcpp::DataFrame data_sailr_cpp_execute(Rcpp::CharacterVector rchars, Rcpp::DataFrame df);
RcppExport SEXP _datasailr_data_sailr_cpp_execute(SEXP rcharsSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rchars(rcharsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(data_sailr_cpp_execute(rchars, df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_datasailr_data_sailr_cpp_execute", (DL_FUNC) &_datasailr_data_sailr_cpp_execute, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_datasailr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
