// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// marshal_faa_di_bruno
Rcpp::List marshal_faa_di_bruno(const Eigen::MatrixXd& Jf, const Eigen::MatrixXd& Hf, const Eigen::MatrixXd& Jg, const Eigen::MatrixXd& Hg);
RcppExport SEXP _RcppEigenAD_marshal_faa_di_bruno(SEXP JfSEXP, SEXP HfSEXP, SEXP JgSEXP, SEXP HgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Jf(JfSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Hf(HfSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Jg(JgSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Hg(HgSEXP);
    rcpp_result_gen = Rcpp::wrap(marshal_faa_di_bruno(Jf, Hf, Jg, Hg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppEigenAD_marshal_faa_di_bruno", (DL_FUNC) &_RcppEigenAD_marshal_faa_di_bruno, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppEigenAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
