// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kernel_DLR_fast
NumericVector kernel_DLR_fast(const List& pCDFlist, const NumericVector& pvalues, const bool adaptive, const double alpha, const bool stepUp, const double zeta, const NumericVector& support);
RcppExport SEXP _FDX_kernel_DLR_fast(SEXP pCDFlistSEXP, SEXP pvaluesSEXP, SEXP adaptiveSEXP, SEXP alphaSEXP, SEXP stepUpSEXP, SEXP zetaSEXP, SEXP supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const bool >::type stepUp(stepUpSEXP);
    Rcpp::traits::input_parameter< const double >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type support(supportSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_DLR_fast(pCDFlist, pvalues, adaptive, alpha, stepUp, zeta, support));
    return rcpp_result_gen;
END_RCPP
}
// kernel_DLR_crit
List kernel_DLR_crit(const List& pCDFlist, const NumericVector& pvalues, const NumericVector& sorted_pv, const bool adaptive, const double alpha, const double zeta, const bool stepUp);
RcppExport SEXP _FDX_kernel_DLR_crit(SEXP pCDFlistSEXP, SEXP pvaluesSEXP, SEXP sorted_pvSEXP, SEXP adaptiveSEXP, SEXP alphaSEXP, SEXP zetaSEXP, SEXP stepUpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sorted_pv(sorted_pvSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type stepUp(stepUpSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_DLR_crit(pCDFlist, pvalues, sorted_pv, adaptive, alpha, zeta, stepUp));
    return rcpp_result_gen;
END_RCPP
}
// kernel_DGR_fast
NumericVector kernel_DGR_fast(const List& pCDFlist, const NumericVector& pvalues, const bool adaptive, const double alpha);
RcppExport SEXP _FDX_kernel_DGR_fast(SEXP pCDFlistSEXP, SEXP pvaluesSEXP, SEXP adaptiveSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_DGR_fast(pCDFlist, pvalues, adaptive, alpha));
    return rcpp_result_gen;
END_RCPP
}
// kernel_DGR_crit
List kernel_DGR_crit(const List& pCDFlist, const NumericVector& pvalues, const NumericVector& sorted_pv, const bool adaptive, const double alpha, const double zeta);
RcppExport SEXP _FDX_kernel_DGR_crit(SEXP pCDFlistSEXP, SEXP pvaluesSEXP, SEXP sorted_pvSEXP, SEXP adaptiveSEXP, SEXP alphaSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sorted_pv(sorted_pvSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_DGR_crit(pCDFlist, pvalues, sorted_pv, adaptive, alpha, zeta));
    return rcpp_result_gen;
END_RCPP
}
// kernel_DPB_fast
NumericVector kernel_DPB_fast(const List& pCDFlist, const NumericVector& pvalues, const bool adaptive, const double alpha, const bool exact);
RcppExport SEXP _FDX_kernel_DPB_fast(SEXP pCDFlistSEXP, SEXP pvaluesSEXP, SEXP adaptiveSEXP, SEXP alphaSEXP, SEXP exactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const bool >::type exact(exactSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_DPB_fast(pCDFlist, pvalues, adaptive, alpha, exact));
    return rcpp_result_gen;
END_RCPP
}
// kernel_DPB_crit
List kernel_DPB_crit(const List& pCDFlist, const NumericVector& pvalues, const NumericVector& sorted_pv, const bool adaptive, const double alpha, const double zeta, const bool exact);
RcppExport SEXP _FDX_kernel_DPB_crit(SEXP pCDFlistSEXP, SEXP pvaluesSEXP, SEXP sorted_pvSEXP, SEXP adaptiveSEXP, SEXP alphaSEXP, SEXP zetaSEXP, SEXP exactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sorted_pv(sorted_pvSEXP);
    Rcpp::traits::input_parameter< const bool >::type adaptive(adaptiveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type exact(exactSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_DPB_crit(pCDFlist, pvalues, sorted_pv, adaptive, alpha, zeta, exact));
    return rcpp_result_gen;
END_RCPP
}
// geom_weight
NumericVector geom_weight(const NumericVector& pvalues, const NumericVector& weights);
RcppExport SEXP _FDX_geom_weight(SEXP pvaluesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type pvalues(pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(geom_weight(pvalues, weights));
    return rcpp_result_gen;
END_RCPP
}
// kernel_wLR_fast
NumericVector kernel_wLR_fast(const NumericVector& qvalues, const NumericVector& weights, double alpha, bool geom_weighting);
RcppExport SEXP _FDX_kernel_wLR_fast(SEXP qvaluesSEXP, SEXP weightsSEXP, SEXP alphaSEXP, SEXP geom_weightingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type qvalues(qvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type geom_weighting(geom_weightingSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_wLR_fast(qvalues, weights, alpha, geom_weighting));
    return rcpp_result_gen;
END_RCPP
}
// kernel_wGR_fast
NumericVector kernel_wGR_fast(const NumericVector& qvalues, const NumericVector& weights, double alpha, bool geom_weighting);
RcppExport SEXP _FDX_kernel_wGR_fast(SEXP qvaluesSEXP, SEXP weightsSEXP, SEXP alphaSEXP, SEXP geom_weightingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type qvalues(qvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type geom_weighting(geom_weightingSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_wGR_fast(qvalues, weights, alpha, geom_weighting));
    return rcpp_result_gen;
END_RCPP
}
// kernel_wPB_fast
NumericVector kernel_wPB_fast(const NumericVector& qvalues, const NumericVector& weights, double alpha, bool geom_weighting, bool exact);
RcppExport SEXP _FDX_kernel_wPB_fast(SEXP qvaluesSEXP, SEXP weightsSEXP, SEXP alphaSEXP, SEXP geom_weightingSEXP, SEXP exactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type qvalues(qvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type geom_weighting(geom_weightingSEXP);
    Rcpp::traits::input_parameter< bool >::type exact(exactSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_wPB_fast(qvalues, weights, alpha, geom_weighting, exact));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FDX_kernel_DLR_fast", (DL_FUNC) &_FDX_kernel_DLR_fast, 7},
    {"_FDX_kernel_DLR_crit", (DL_FUNC) &_FDX_kernel_DLR_crit, 7},
    {"_FDX_kernel_DGR_fast", (DL_FUNC) &_FDX_kernel_DGR_fast, 4},
    {"_FDX_kernel_DGR_crit", (DL_FUNC) &_FDX_kernel_DGR_crit, 6},
    {"_FDX_kernel_DPB_fast", (DL_FUNC) &_FDX_kernel_DPB_fast, 5},
    {"_FDX_kernel_DPB_crit", (DL_FUNC) &_FDX_kernel_DPB_crit, 7},
    {"_FDX_geom_weight", (DL_FUNC) &_FDX_geom_weight, 2},
    {"_FDX_kernel_wLR_fast", (DL_FUNC) &_FDX_kernel_wLR_fast, 4},
    {"_FDX_kernel_wGR_fast", (DL_FUNC) &_FDX_kernel_wGR_fast, 4},
    {"_FDX_kernel_wPB_fast", (DL_FUNC) &_FDX_kernel_wPB_fast, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_FDX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
