# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_peltuv <- function(data, str_cost_func, alpha, m) {
    .Call('_changepoint_mv_rcppeigen_peltuv', PACKAGE = 'changepoint.mv', data, str_cost_func, alpha, m)
}

rcppeigen_tail_costs <- function(data, str_cost_func, m) {
    .Call('_changepoint_mv_rcppeigen_tail_costs', PACKAGE = 'changepoint.mv', data, str_cost_func, m)
}

