# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmn_mu_S2 <- function(rnd_vec, p, mu, S) {
    invisible(.Call(`_BayesLN_rmn_mu_S2`, rnd_vec, p, mu, S))
}

MCMC_alg <- function(y, X, Z_list, K_gamma_list, S_beta_pri, l_s, l_t, d_s, d_t, g_s, g_t, s, nsamp, verbose, beta_init, sigma2_init, tau2_init) {
    .Call(`_BayesLN_MCMC_alg`, y, X, Z_list, K_gamma_list, S_beta_pri, l_s, l_t, d_s, d_t, g_s, g_t, s, nsamp, verbose, beta_init, sigma2_init, tau2_init)
}

post_pred <- function(output, Xrep, Zrep_list, s, nsamp) {
    .Call(`_BayesLN_post_pred`, output, Xrep, Zrep_list, s, nsamp)
}

