# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_kmeans_cuda <- function(samples, clusters, tolerance_sexp, init_sexp, yinyang_t_sexp, metric_sexp, average_distance_bool, seed_sexp, device, verbosity) {
    .Call('_kmcudaR_r_kmeans_cuda', PACKAGE = 'kmcudaR', samples, clusters, tolerance_sexp, init_sexp, yinyang_t_sexp, metric_sexp, average_distance_bool, seed_sexp, device, verbosity)
}

r_knn_cuda <- function(k, samples, centroids_sexp, assignments_sexp, metric_sexp, device, verbosity) {
    .Call('_kmcudaR_r_knn_cuda', PACKAGE = 'kmcudaR', k, samples, centroids_sexp, assignments_sexp, metric_sexp, device, verbosity)
}

