# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_iterate <- function(dx, dminxy, Sx_base, Sy, verbose = FALSE) {
    .Call(`_cnaOpt_C_iterate`, dx, dminxy, Sx_base, Sy, verbose)
}

